main:
  - name: Book Travel
    identifier: support
    url: https://jeremybouse.inteletravel.com
    weight: 80
    params:
      icon: 
        vendor: bs
        name: passport
      description: My travel booking portal.

  - name: Viator Tours
    parent: support
    url: https://www.viator.com/?pid=P00011640&uid=U00595707&mcid=58086&currency=USD
    weight: 10
    params:
      icon:
        vendor: bs
        name: calendar-event
        color: green
      description: Viator booking portal.

  - name: Virgin Voyages
    parent: support
    url: https://www.virginvoyages.com/book/voyage-planner/find-a-voyage?cabins=1&currencyCode=USD&agentId=204567&agencyId=354&bookingChannel=FMLINK
    weight: 11
    params:
      icon:
        vendor: fas
        name: ship
        color: red
      description: Virgin Voyages booking portal.

  - name: Shore Excursions
    parent: support
    url: https://www.shoreexcursionsgroup.com/?id=81171&data=bousetravel@undergrid.net
    weight: 12
    params:
      icon:
        vendor: bs
        name: calendar-event
        color: blue
      description: Shore Excursions booking portal.

#   - name: Discussion
#     parent: support
#     url: https://github.com/orgs/hbstack/discussions
#     weight: 12
#     params:
#       icon:
#         vendor: font-awesome-regular
#         name: comments
#         color: green
#       description: Ask questions and share your ideas.

#   - name: Bug Report
#     parent: support
#     url: https://github.com/orgs/hbstack/discussions/new?category=issues-and-bugs
#     weight: 13
#     params:
#       icon:
#         vendor: font-awesome-solid
#         name: bug
#         color: red
#       description: Tell us about a bug or issue.

#   - name: Feature Request
#     parent: support
#     url: https://github.com/orgs/hbstack/discussions/new?category=ideas
#     weight: 14
#     params:
#       icon:
#         vendor: font-awesome-regular
#         name: lightbulb
#         color: orange
#       description: Suggest new or updated features.
  
#   - name: Mastodon
#     parent: support
#     url: https://techhub.social/@hbstack
#     weight: 16
#     params:
#       icon:
#         vendor: simple
#         name: mastodon
#       description: Follow us on Mastodon to get latest updates.
