repos:
  - repo: local
    hooks:
      - id: resize-jpgs
        name: Resize JPGs in assets/images
        entry: python assets/images/resize_jpgs.py
        language: system
        files: ^assets/images/.*\.jpg$
        staged: true