# see https://hugomods.com/en/docs/google-analytics/.
services:
  googleAnalytics:
    id: G-5S02G6QQ9F # Google Analytics, please make sure you've imported the Google Analytics module.
  disqus:
    shortname: bousetravels # The Disqus shortname.
