name: Post RSS Summaries to Socials

on:
  schedule:
    - cron: '0 7 * * *' # Runs every day at 7am UTC
  workflow_dispatch:

jobs:
  post-to-socials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser openai atproto requests beautifulsoup4

      - name: Restore seen_rss_posts.txt cache
        uses: actions/cache@v4
        with:
          path: .github/seen_rss_posts.txt
          key: seen-rss-posts-${{ runner.os }}
          restore-keys: |
            seen-rss-posts-

      - name: Run rss-to-social script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BLUESKY_HANDLE: ${{ vars.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
          RSS_FEED_URL: ${{ vars.RSS_FEED_URL }}
        run: |
          python .github/rss-to-social.py

      - name: Save seen_rss_posts.txt cache
        uses: actions/cache@v4
        with:
          path: .github/seen_rss_posts.txt
          key: seen-rss-posts-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            seen-rss-posts-
